version: '3.8'

services:
  wordmasters:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wordmasters-app
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NODE_ENV=production
    volumes:
      # Persist words.json data
      - ./words.json:/app/words.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
